---
apiVersion: v1
kind: Namespace
metadata:
  name: meshery
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meshery
  namespace: meshery
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: smi-conformance
    release: smi-conformance
  name: smi-conformance
  namespace: meshery
spec:
  selector:
    matchLabels:
      app: smi-conformance
      release: smi-conformance
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: smi-conformance
        release: smi-conformance
    spec:
      containers:
      - name: smi-conformance
        image: hulkbuster/smi-conformance:latest
        imagePullPolicy: Always
        name: smi-conformance
        ports:
        - containerPort: 10008
          name: grpc
          protocol: TCP
        resources:
          limits:
            cpu: "500m"
            memory: 1000Mi
          requests:
            cpu: "200m"
            memory: 500Mi
      restartPolicy: Always
      serviceAccount: meshery
      serviceAccountName: meshery
---
apiVersion: v1
kind: Service
metadata:
  name: smi-conformance
  namespace: meshery
  labels:
    app: smi-conformance
spec:
  type: NodePort
  ports:
  - name: smi-conformance
    port: 10008
    targetPort: 10008
    protocol: TCP 
  selector:
    app: smi-conformance 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: ServiceAccount
  name: meshery
  namespace: meshery
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
